# Assignment 1: False Alarms

Author:  
Fredrik Boglind

### Imports

In [14]:
import pandas as pd
# import torch
# import torch.nn as nn
# import torch.optim as optim
import numpy as np
import wfdb  # For reading waveform files
import os
from pathlib import Path

import sklearn as sk
# import xgboost as xgb
import seaborn as sns
import matplotlib.pyplot as plt
from utility_functions import *
# we use code from the VTaC repository for filtering and standardizing: https://github.com/ML-Health/VTaC
# from filtering import *
# from standardize import *

### Load data

We load the raw dataset for the task.

In [ ]:
DATA_DIR = Path('raw_data/vtac-a-benchmark-dataset-of-ventricular-tachycardia-alarms-from-icu-monitors-1.0/')
# Load and merge
labels = pd.read_csv(DATA_DIR / 'event_labels.csv')
splits = pd.read_csv(DATA_DIR / 'benchmark_data_split.csv')
df = splits.merge(labels, on=['record', 'event'])

df.head()

   split  record        event  decision
0  train  003c13  003c13_0115     False
1  train  003c13  003c13_0126     False
2  train  004bad  004bad_0015     False
3  train  004bad  004bad_1115     False
4  train  004bad  004bad_1426     False

In [24]:
df['decision'].value_counts()

decision
False    3596
True     1441
Name: count, dtype: int64

In [25]:
df['decision'].value_counts()

decision
False    3596
True     1441
Name: count, dtype: int64

In [26]:
pd.crosstab(df['split'], df['decision'])

decision  False  True
split
test        345    137
train      2897   1163
val         354    141

In [ ]:
# Load both files
labels_df = pd.read_csv(DATA_DIR / 'event_labels.csv')
splits_df = pd.read_csv(DATA_DIR / 'benchmark_data_split.csv')

# Merge on record AND event
df = splits_df.merge(labels_df, on=['record', 'event'], how='inner')

print(f"Total samples: {len(df)}")
print(f"\nSplit distribution:")
print(df['split'].value_counts())
print(f"\nLabel distribution (decision):")
print(df['decision'].value_counts())
print(f"\nClass balance: {df['decision'].mean():.1%} True alarms")

# # Cross-tabulation
# print(f"\nLabels per split:")
# print(pd.crosstab(df['split'], df['decision']))

Total samples: 5037

Split distribution:
split
train    4060
val       495
test      482
Name: count, dtype: int64

Label distribution (decision):
decision
False    3596
True     1441
Name: count, dtype: int64

Class balance: 28.6% True alarms

Labels per split:
decision  False  True
split
test        345    137
train      2897   1163
val         354    141

### Data exploration

In [ ]:
# Questions to answer:
# - How many True vs False alarms? (class balance)
# - Which signals are available in each record?
# - What does missing data look like?
# - What's the signal duration?

Load the event labels and data splits.

In [ ]:
# Event labels - contains the TRUE/FALSE alarm labels
labels_df = pd.read_csv(DATA_DIR / 'event_labels.csv')
print("=== Event Labels ===")
print(f"Shape: {labels_df.shape}")
print(f"Columns: {labels_df.columns.tolist()}")
print(f"\nFirst few rows:\n{labels_df.head()}")
print(f"\nLabel distribution:\n{labels_df['decision'].value_counts()}")

# Benchmark splits - train/val/test assignments
splits_df = pd.read_csv(DATA_DIR / 'benchmark_data_split.csv')
print("\n=== Data Splits ===")
print(f"Shape: {splits_df.shape}")
print(f"Columns: {splits_df.columns.tolist()}")
print(f"\nSplit distribution:\n{splits_df['split'].value_counts()}")

### Preprocessing

In [ ]:
# We use code from the VTaC repository for filtering and standardizing: https://github.com/ML-Health/VTaC
def load_metadata():
    """ - Loads label and split metadata from CSV files.
        - Inputs: None
        - Outputs: Tuple of pd.DataFrame: labels_df and splits_df"""
    
    # Event labels: TRUE/FALSE alarm labels
    labels_df = pd.read_csv(DATA_DIR / 'event_labels.csv')
    print("=== Event Labels ===")
    print(f"Shape: {labels_df.shape}")
    print(f"Columns: {labels_df.columns.tolist()}")
    print(f"\nFirst few rows:\n{labels_df.head()}")
    print(f"\nLabel distribution:\n{labels_df['decision'].value_counts()}")
    
    # Benchmark splits: train/val/test splits
    splits_df = pd.read_csv(DATA_DIR / 'benchmark_data_split.csv')
    print("\n=== Data Splits ===")
    print(f"Shape: {splits_df.shape}")
    print(f"Columns: {splits_df.columns.tolist()}")
    print(f"\nSplit distribution:\n{splits_df['split'].value_counts()}")
    
    return labels_df, splits_df

## Task 1: Predict whether or not an alarm is True or False.

This section should contain the solution of task 1.

It is mandatory to maintain the headings for each task.  
OPTIONALLY, you can use one level down (###) to organize subsessions of the assignments.

Use markdown cells like this one to include:
- Discussion points.
- References to specific sources of code that you might have used to solve the assignment.
- General commentas and explanations about your solution.

In [ ]:
# Always use comments in the code to document specific steps

### Data Exploration

~~## Task 2: This is the title of task 2~~

## Results and Discussion

This section should contain:
- Results.
- Summary of best model performance:
    - Name of best model file as saved in /models.
    - Relevant scores such as: accuracy, precision, recall, F1-score, etc.
- Key discussion points.